export const productFlow = [
  { 'key': '成品类别', 'value': 'productType', 'type': 2, 'list': 'listH016009', 'noNeed': true },
  { 'key': '流程名称', 'value': 'flowName', 'noNeed': true },
  { 'key': '流程编号', 'value': 'flowCode', 'noNeed': true },
  { 'key': '所属部门', 'value': 'department', 'type': 2, 'list': 'listDeptDrop', 'noNeed': true },
  { 'key': '英文名称', 'value': 'enName', 'noNeed': true },
  { 'key': '类别', 'value': 'type', 'type': 2, 'list': 'listH017', 'noNeed': true },
  { 'key': '镶石工艺', 'value': 'stoneCraft', 'type': 2, 'list': 'listGemSetProcessDropDown', 'noNeed': true },
  {
    'key': '是否外发',
    'value': 'isOutbound',
    'type': 6,
    'arr': [{ 'key': '是', 'value': '1' }, { 'key': '否', 'value': '0' }],
    'initValue': '0',
  },
  { 'key': '生产流程允许损耗(%)', 'value': 'isWastage', 'noNeed': true },
  { 'key': '出货重量范围', 'value': 'weightRange', 'noNeed': true },
  { 'key': '标准工时', 'value': 'workingHour', 'noNeed': true },
];

export const productProcess = [
  {
    'key': '产品编号',
    'value': 'productId',
    'clickFn': 'showProductModalFunc',
    'text': '选择产品编号',
    'type': 3,
  },
  { 'key': '客户货号', 'value': 'custoerProductNo', 'noNeed': true, 'type': 7 },
  { 'key': '类别', 'value': 'productTypeName', 'noNeed': true, 'type': 7 },
  { 'key': '成色名称', 'value': 'productColorName', 'noNeed': true, 'type': 7 },
  { 'key': '宝石颜色', 'value': 'gemColorName', 'noNeed': true, 'type': 7 },
  { 'key': '电镀颜色', 'value': 'platingColorName', 'noNeed': true, 'type': 7 },
  { 'key': '成品重量', 'value': 'finishedWeight', 'number': true },
  { 'key': '产品系列', 'value': 'productLineName', 'noNeed': true },
  { 'key': '产品报价系数', 'value': 'productLineCoefficientQuotation', 'type': 7 },
  { 'key': '计量单位', 'value': 'unitOfMeasurementName', 'type': 7 },
  { 'key': '重量单位', 'value': 'unitOfWeightName', 'type': 7 },
  { 'key': '前次工费/克', 'value': 'lastCount', 'number': true, 'type': 7 },
  { 'key': '最高工费/克', 'value': 'topCount', 'number': true, 'type': 7 },
  { 'key': '实际工费/克', 'value': 'actualCount', 'number': true, 'noNeed': true },
  { 'key': '此次工费/克', 'value': 'nowCount', 'number': true },
  {
    'key': '是否计石重',
    'value': 'isWeighStones',
    'type': 6,
    'arr': [{ 'key': '是', 'value': 'H009001' }, { 'key': '否', 'value': 'H009002' }],
    'initValue': 'H009001',
  },
  { 'key': '石材重量', 'value': 'stonesWeight', 'noNeed': true, 'number': true },
  { 'key': '主材重量', 'value': 'mainMaterialWeight', 'noNeed': true, 'number': true },
  { 'key': '石材价', 'value': 'stonePrice', 'noNeed': true, 'number': true },
  { 'key': '字印编码', 'value': 'markingId', 'type': 2, 'list': 'markinglist', 'noNeed': true },
  { 'key': '字印英文名', 'value': 'markingEnName', 'noNeed': true, 'type': 7 },
  { 'key': '字印价/件', 'value': 'markingPrice', 'number': true },
  { 'key': '包装单价/件', 'value': 'packPrice', 'number': true, 'noNeed': true },
  { 'key': '单价', 'value': 'price', 'number': true },
  { 'key': '报价数量', 'value': 'qty', 'number': true, 'noNeed': true, 'type': 7 },
  { 'key': '报价金额', 'value': 'quotedAmount', 'number': true, 'noNeed': true, 'type': 7 },
  { 'key': '报价重量范围', 'value': 'quotedWeightRange', 'noNeed': true },
  { 'key': '产品工费/件', 'value': 'productCost', 'number': true },
  { 'key': '产品长度', 'value': 'productLength', 'noNeed': true, 'number': true },
  { 'key': '长度描述', 'value': 'lengthDescription', 'noNeed': true },
  { 'key': '长度单位', 'value': 'lengthUnit', 'noNeed': true },
  { 'key': '戒围标准', 'value': 'ringAroundStId', 'noNeed': true },
  { 'key': '戒围号', 'value': 'sizeCodeId' },
  { 'key': '备注', 'value': 'remark', 'noNeed': true },
  { 'key': '客户要求', 'value': 'customerRequirements', 'noNeed': true },
];


export default {
  productFlow,
  productProcess
}
