import {statusConvert,YoNConvert} from '@/utils/convert';

export const piHead = [
  { 'key': '订单号码', 'value': 'piNo' },
  { 'key': '原始订单号码', 'value': 'originalPiNo' },
  { 'key': '订单日期', 'value': 'piDate' ,'data':'YYYY-MM-dd'},
  { 'key': '客户编号', 'value': 'customerNo' },
  { 'key': '客户简称', 'value': 'customerShotName' },
  { 'key': '终客编号', 'value': 'endNo' },
  { 'key': '终客简称', 'value': 'endShotName' },
  { 'key': '订单类别', 'value': 'piTypeName' },
  { 'key': '报价方式', 'value': 'quoteMethodName' },
  { 'key': '币种', 'value': 'currency'},
  { 'key': '汇率', 'value': 'ratio'},
  { 'key': '客户采购单号', 'value': 'poNo'},
  { 'key': '主材价', 'value': 'mainMaterialPrice'},
  { 'key': '总数', 'value': 'totalCount'},
  { 'key': '总重', 'value': 'totalWeightQuotation'},
  { 'key': '订单金额', 'value': 'totalQuotation'},
  { 'key': '要求预付款', 'value': 'advancePayment'},
  { 'key': '要求交货期', 'value': 'deliveryTime','data':'YYYY-MM-dd'},
  { 'key': '产品说明', 'value': 'productDescription'},
  { 'key': '包装说明', 'value': 'packExplains' },
  { 'key': '客户要求', 'value': 'requirement' },
  { 'key': '状态', 'value': 'status',"convert":statusConvert },
  { 'key': '备注', 'value': 'remark' },
];

export const piDetail =[
  { 'key': '序号', 'value': 'version' },
  { 'key': '名称', 'value': 'zhName' },
  { 'key': '编号', 'value': 'productNo' },
  { 'key': '类别', 'value': 'productTypeName' },
  { 'key': '宝石颜色', 'value': 'gemColorName' },
  { 'key': '成色重量', 'value': 'finishedWeight' },
  { 'key': '电镀', 'value': 'platingColorName' },
  { 'key': '成色', 'value': 'productColorName' },
  { 'key': '产品来源', 'value': 'sourceOfProduct' },
  { 'key': '模具', 'value': 'mouldNoName' },
  { 'key': '产品系列', 'value': 'productLineName' },
  { 'key': '品牌', 'value': 'brandNo' },
  { 'key': '此次工费', 'value': 'nowCount' },
  { 'key': '实际工费', 'value': 'actualCount' },
  { 'key': '订单数量', 'value': 'totalCount' },
  { 'key': '单价', 'value': 'price' },
  { 'key': '订单重量', 'value': 'totalWeightQuotation' },
  { 'key': '订单金额', 'value': 'totalQuotation'  },
  { 'key': '字印编码', 'value': 'markingNo'  },
  { 'key': '字印中文名称', 'value': 'markingNoName' },
  { 'key': '字印单价', 'value': 'markingPrice' },
  { 'key': '包装单价', 'value': 'packPrice' },
  { 'key': '产品长度', 'value': 'productLength' },
  { 'key': '产品单位', 'value': 'unitOfWeight' },
  { 'key': '产品戒围', 'value': 'sizeCodeId' },
  { 'key': '戒围与数量', 'value': '' },
  { 'key': '备注', 'value': 'remark'  },
];


export default {
  piHead,
  piDetail,
};
